#!/usr/bin/env bash
#  Script for calling from the upnpc-daemon.service
#  Copyright (C) 2021 Alexey Svistunov <svalx@svalx.net>

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

HOST=`uname -n`
I=0

while [ -v EXT_PORT$I ];
do
	EXT_PORT="EXT_PORT$I"
       	INT_PORT="INT_PORT$I"
       	PROTO="PROTO$I"
	SERVICE="SERVICE$I"

	upnpc -e "${!SERVICE} on $HOST" -r "${!INT_PORT}" "${!EXT_PORT}" "${!PROTO}"

	I=$(( $I + 1 ))
done
